name: Create Artifact
on:
  workflow_dispatch:

jobs:
  upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Create File
        run: echo "This is the content of artifact 1" > artifact.txt
      - name: Upload Artifact
        uses: actions/upload-artifact@v6
        with:
          name: artifact
          path: artifact.txt
  create-zip:
    needs: upload-artifact
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v7
        with:
          path: artifact
          merge-multiple: true
      - name: Debug
        run: pwd && ls
      - name: Create zip file
        run: zip -r artifact.zip artifact
      - name: Upload zip file
        uses: actions/upload-artifact@v6
        with:
          name: artifact-zip
          path: artifact.zip
