name: Receive Input
on:
  workflow_dispatch:
    inputs:
      example_input:
        description: 'An example input'
        required: true
        default: 'Default value'
        type: string
  
jobs:
  receive_input:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: echo "Received input > ${{ github.event.inputs.example_input }}"
